version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: poemdb
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
